<?php
$this->openHtml(FALSE);
$this->openHead( [], FALSE );
$this->Meta( ['charset'=>"utf-8"], FALSE );
$this->Title( ['text'=>"Untitled Page"], FALSE );
$this->Meta( ['name'=>"generator", 'content'=>"WYSIWYG Web Builder 14 Trial Version - http://www.wysiwygwebbuilder.com"], FALSE );
$this->Link( ['href'=>"wb.validation.css", 'rel'=>"stylesheet"], FALSE );
$this->Link( ['href'=>"contact_us.css", 'rel'=>"stylesheet"], FALSE );
$this->Link( ['href'=>"index.css", 'rel'=>"stylesheet"], FALSE );
$this->Script( ['src'=>"jquery-1.12.4.min.js"], FALSE );
$this->Script( FALSE);
$this->Script( ['src'=>"wb.validation.min.js"], FALSE );
$this->Script( FALSE);
$this->Script( ['src'=>"index.js"], FALSE );
$this->Script( FALSE);
$this->closeHead( FALSE );
$this->openBody( [], FALSE );
$this->openDiv( ['class'=>"gd-grid-17"], FALSE );
$this->openDiv( ['class'=>"gd-grid-5"], FALSE );
$this->Image( ['src'=>"/INTERSHOP/static/WFS/DGISupply-US-Site/-/DGISupply-US/en_US/hlr-system/DGI_DAC/Intershop/Section%20Images/170px/AP.jpg", 'data-test'=>"true", 'data-type'=>"CIL", 'data-view-value'=>"CategoryImage0", 'alt'=>"AP Category Internal Image View CIL"], FALSE );
$this->closeDiv( FALSE );
$this->openDiv( ['class'=>"gd-grid-11"], FALSE );
$this->openH1( ['text'=>"Abrasives"], FALSE );
$this->openDiv( ['class'=>"dgi-category-bullets"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"The desired finish, hardness of the work piece, and application should determined the type of abrasive used."], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Quality abrasives should not only provide the desired finish but last longer and improve productivity."], FALSE );
$this->closeUL( FALSE);
$this->closeDiv( FALSE );
$this->closeDiv( FALSE );
$this->closeDiv( FALSE );
$this->closeBody( FALSE );
$this->closeHtml(FALSE);
?>