<?php
$this->openHtml(FALSE);
$this->openHead( [], FALSE );
$this->Meta( ['charset'=>'utf-8'], FALSE );
$this->Title( [], FALSE );
$this->Meta( ['name'=>'generator', 'content'=>'WYSIWYG Web Builder 14 Trial Version - http://www.wysiwygwebbuilder.com'], FALSE );
$this->Link( ['href'=>'wb.validation.css', 'rel'=>'stylesheet'], FALSE );
$this->Link( ['href'=>'contact_us.css', 'rel'=>'stylesheet'], FALSE );
$this->Link( ['href'=>'index.css', 'rel'=>'stylesheet'], FALSE );
$this->Script( ['src'=>'jquery-1.12.4.min.js'], FALSE );
$this->Script( ['src'=>'wb.validation.min.js'], FALSE );
$this->Script( ['src'=>'index.js'], FALSE );
$this->openBody( [], FALSE );
$this->closeDiv( [], FALSE );
$this->closeDiv( [], FALSE );
$this->openDiv( ['id'=>'pageContent', 'class'=>'pageContent'], FALSE );
$this->openDiv( ['id'=>'leftMenu'], FALSE );
$this->openDiv( ['id'=>'section-menu'], FALSE );
$this->openUL( [], FALSE );
$this->openLI( ['style'=>'margin-bottom:10px;'], FALSE );
$this->aTag( ['class'=>'menuitem', 'style'=>'text-decoration: none;', 'text' =>'Products'], FALSE );
$this->openDiv( ['id'=>'products', 'class'=>'categoriesDiv'], FALSE );
$this->openUL( [], FALSE );
$this->closeUL( [], FALSE );
$this->closeDiv( [], FALSE );
$this->closeLI( [], FALSE );
$this->openLI( ['style'=>'margin-bottom:10px;'], FALSE );
$this->aTag( ['class'=>'menuitem', 'style'=>'text-decoration: none;', 'text' =>'Manufacturer'], FALSE );
$this->openDiv( ['id'=>'refineBrands1', 'class'=>'refineBrands1'], FALSE );
$this->openDiv( ['id'=>'refineBrands2', 'class'=>'refineBrands2'], FALSE );
$this->openUL( [], FALSE );
$this->closeUL( [], FALSE );
$this->closeDiv( [], FALSE );
$this->closeDiv( [], FALSE );
$this->closeLI( [], FALSE );
$this->closeBody( [], FALSE );
$this->closeHtml(FALSE);
?>