<?php
$this->openHtml(FALSE);
$this->openHead( [], FALSE );
$this->Meta( ['charset'=>"utf-8"], FALSE );
$this->Title( ['text'=>"Untitled Page"], FALSE );
$this->Meta( ['name'=>"generator", 'content'=>"WYSIWYG Web Builder 14 Trial Version - http://www.wysiwygwebbuilder.com"], FALSE );
$this->Link( ['href'=>"wb.validation.css", 'rel'=>"stylesheet"], FALSE );
$this->Link( ['href'=>"contact_us.css", 'rel'=>"stylesheet"], FALSE );
$this->Link( ['href'=>"index.css", 'rel'=>"stylesheet"], FALSE );
$this->Script( ['src'=>"jquery-1.12.4.min.js"], FALSE );
$this->Script( FALSE);
$this->Script( ['src'=>"wb.validation.min.js"], FALSE );
$this->Script( FALSE);
$this->Script( ['src'=>"index.js"], FALSE );
$this->Script( FALSE);
$this->closeHead( FALSE );
$this->openBody( [], FALSE );
$this->openDiv( ['id'=>"TreeView"], FALSE );
$this->openUL( ['id'=>"master"], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"users", 'checked,'], FALSE );
$this->Label( ['for'=>"users", 'text'=>"Abrasives"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Bra"], FALSE );
$this->Label( ['for'=>"Bra", 'text'=>"Coated Abrasives"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Document"], FALSE );
$this->Label( ['for'=>"Document", 'text'=>"Coated Abrasives Discs"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Center Arbor Hole Discs"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Hook & Loop Discs"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Hook & Loop Discs"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"PSA Discs"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Quick Change Discs"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Quick Change Discs", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Picture"], FALSE );
$this->Label( ['for'=>"Picture", 'text'=>"Coated Abrasives Belts"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive File Belts"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Narrow Belts"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Portable Belts"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Wide Belts"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Coated Abrasive Wide Belts", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Flower"], FALSE );
$this->Label( ['for'=>"Flower", 'text'=>"Coated Abrasives Rolls"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Cloth Rolls"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Paper Rolls"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Microfinishing Film Rolls"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Microfinishing Film Rolls", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Por"], FALSE );
$this->Label( ['for'=>"Por", 'text'=>"Coated Abrasives Sheets(230)"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Sheets for Dry Applications"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Wet or Dry Abrasive Sheets"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Wet or Dry Abrasive Sheets", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Site"], FALSE );
$this->Label( ['for'=>"Site", 'text'=>"Flap Discs(271)"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Type 27 Coated Abrasive Flap Discs"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Type 27 Coated Abrasive Flap Discs"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Type 27 Coated Abrasive Flap Discs", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Site"], FALSE );
$this->Label( ['for'=>"Site", 'text'=>"Flap Wheels(271)"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Mounted Flap Wheels"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Unmounted Flap Wheels"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Unmounted Flap Wheels", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Site"], FALSE );
$this->Label( ['for'=>"Site", 'text'=>"Bands & Cartridge Rolls(352)"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Bands"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Cartridge Rolls"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Coated Abrasive Cartridge Rolls", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Site"], FALSE );
$this->Label( ['for'=>"Site", 'text'=>"Bands & Cartridge Rolls(352)"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Bands"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Coated Abrasive Cartridge Rolls"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Coated Abrasive Cartridge Rolls", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Site"], FALSE );
$this->Label( ['for'=>"Site", 'text'=>"Sponges(31)"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Abrasive Flexible Sanding Sponges"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Abrasive Softback Sanding Sponges"], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Abrasive Surface Sanding Sponges"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Abrasive Surface Sanding Sponges", 'text'=>""], FALSE );
$this->openLI( [], FALSE );
$this->Input( ['type'=>"checkbox", 'id'=>"Site"], FALSE );
$this->Label( ['for'=>"Site", 'text'=>"Square & Cross Pads(8)"], FALSE );
$this->openUL( [], FALSE );
$this->openLI( [], FALSE );
$this->closeLI( ['text'=>"Square Pads"], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Square Pads", 'text'=>""], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Square Pads", 'text'=>"", 'text'=>""], FALSE );
$this->closeUL( FALSE);
$this->closeLI( ['text'=>"Square Pads", 'text'=>"", 'text'=>"", 'text'=>""], FALSE );
$this->closeUL( FALSE);
$this->closeDiv( FALSE );
$this->closeBody( FALSE );
$this->closeHtml(FALSE);
?>